spring:
  datasource:
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e3mall?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10

server:
  port: 8081

logging:
  level:
    fun.guoke.service.item.mapper: debug